export default {
  SET_LOADING: 'SET_LOADING',
  TOGGLE_LOADING: 'TOGGLE_LOADING',
  SET_USER: 'SET_USER',
  CLEAR_USER: 'CLEAR_USER',
  SET_MERCHANT: 'SET_MERCHANT',
  CLEAR_MERCHANT: 'CLEAR_MERCHANT',
  SET_STATE: 'SET_STATE',
}